services:
  proxy:
    build:
      context: .
    restart: on-failure
    networks:
      - api_network
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
